# Change these first
owner: UniExperiment # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository
user-agent: niksavc02

sites:
  - name: Unicode
    url: https://unirev.xyz
    logoUrl: https://raw.githubusercontent.com/UniExperiment/status/master/9.webp
  - name: Client Setup
    url: https://setup.unirev.xyz/
    logoUrl: https://raw.githubusercontent.com/UniExperiment/status/master/9.webp
  - name: API
    url: https://api.unirev.xyz/
    logoUrl: https://raw.githubusercontent.com/UniExperiment/status/master/9.webp
  - name: Asset Delivery
    url: https://unirev.xyz/asset/
    logoUrl: https://raw.githubusercontent.com/UniExperiment/status/master/9.webp
    expectedStatusCodes:
      - 400

assignees:
  - niksavc02

status-website:
  theme: night
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: uniexperiment.github.io/status
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/UniExperiment/status/master/9.webp
  name: Unicode
  introTitle: "Unicode Status"
  navbar:
    - title: Unicode
      href: https://www.unirev.xyz
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

i18n:
  footer: "[Unicode](https://www.unirev.xyz) 2024-2024. This page is [open source]($REPO)."

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
